init -1 python:
    JOUR_DISC_1304 = "13 avr."
    dialogue = ghostnet_dialogue_builder(JOUR_DISC_1304)

    ghostnet_register_discussion(
        discussion_id="DISC-13-04",
        name="SESSION ENTRANTE",
        summary="Conversation interceptée. Défilement manuel en mode lecture.",
        day=JOUR_DISC_1304,
        participants=["romie", "bryonn"],
        device_owner="romie",
        unlock_tag="TAG:CARTE_PLATINUM",
        unlocks_discussions=["DISC-21-04"],
        unlocks_content=["Dossier achats Bonton"],
        entries=[
            dialogue("romie", "Bryonn je suis en PLS là je te jure"),
            dialogue("romie", "J’ai jamais été aussi vénère pour 89 crédits de ma vie"),
            dialogue("romie", "Le top noir asymétrique avec les découpes latérales, tu sais celui que je t’ai montré en story la semaine dernière ?"),
            dialogue("romie", "Ils ont mis un QR en vitrine : 60 % aujourd’hui seulement, les 500 premières"),
            dialogue("romie", "J’étais genre ‘c’est moi ça’ direct"),
            dialogue("romie", "J’ai scanné, ça a chargé… et PAF. Erreur 403. Accès refusé"),
            dialogue("romie", "Le caissier m’a regardée comme si j’avais essayé de voler la boutique"),
            dialogue("romie", "J’ai insisté genre ‘mais la pub disait…’ il m’a sorti ‘les conditions ont changé ce matin désolé mademoiselle’"),
            dialogue("romie", "Mademoiselle. Il a vraiment dit mademoiselle. J’avais envie de lui balancer le cintre dans la tronche"),
            dialogue("bryonn", "Attends… ils ont changé les conditions EN JOURNÉE ?"),
            dialogue("bryonn", "C’est du foutage de gueule niveau 9000 ça"),
            dialogue("bryonn", "Ils font ça tout le temps maintenant. Ils balancent le QR pour faire venir du monde, tracker les scans, et après ils verrouillent"),
            dialogue("romie", "Ouais bah moi j’ai pas capté le piège"),
            dialogue("romie", "Du coup j’ai payé plein pot parce que… ben j’ai essayé en cabine et j’ai trop kiffé"),
            dialogue("romie", "Genre vraiment trop"),
            dialogue("romie", "Les découpes sont placées exactement où il faut, ça fait un décolleté latéral hyper osé sans être vulgaire"),
            dialogue("romie", "Et avec la jupe grise réglementaire en dessous… putain Bryonn c’est criminel ce que ça fait aux hanches"),
            dialogue("romie", "Je me suis sentie… je sais pas… puissante ? Sexy en mode ‘je m’en fous de vos règles’ ?"),
            dialogue("romie", "J’ai fait genre 15 selfies dans la cabine pour être sûre"),
            dialogue("bryonn", "T’as pris des photos en cabine ?"),
            dialogue("bryonn", "Envoie stp je suis au dépôt là j’ai besoin d’un shoot de motivation pour finir ce shift de merde"),
            dialogue("romie", "[romie_pic001.png]"),
            dialogue("romie", "Voilà. Celle-là est pas trop pourrie en lumière"),
            dialogue("romie", "Tu vois le truc ? Ça tombe nickel sur les côtes, on devine sans tout montrer"),
            dialogue("romie", "J’ai hésité à l’enlever direct et le remettre sur le cintre… mais non. Je l’ai pris"),
            dialogue("romie", "89 crédits de rage mais 89 crédits de slay aussi"),
            dialogue("bryonn", "… ok wow"),
            dialogue("bryonn", "Romie t’es en train de me tuer là"),
            dialogue("bryonn", "Je te jure je viens de zoomer trois fois"),
            dialogue("bryonn", "Putain, j'espère que mes collègues vont pas voir ça ..."),
            dialogue("bryonn", "[bryonn_pic001.png]"),
            dialogue("bryonn", "Garde-le sur toi ce soir. S’il te plaît"),
            dialogue("romie", "Ah ouais ? Tu kiffes ?"),
            dialogue("romie", "Je me disais aussi que ça te ferait un peeetit truc"),
            dialogue("romie", "J’ai mis le top + la jupe en rentrant dans le métro. J’ai senti tous les regards"),
            dialogue("romie", "Même les drones m’ont suivi plus longtemps que d’habitude"),
            dialogue("romie", "Je sais pas si c’est l’adrénaline ou le tissu mais j’étais… chaude. Genre vraiment"),
            dialogue("romie", "Là je suis rentrée, j’ai viré les chaussures, je suis sur le canapé en string et juste le top"),
            dialogue("romie", "Et je pense à toi qui rentres avec ta gueule fatiguée de livreur"),
            dialogue("romie", "J’ai envie que tu me plaques contre le mur dès que la porte claque"),
            dialogue("romie", "Que tu glisses tes mains sous les découpes sans rien dire"),
            dialogue("romie", "Et que tu me fasses oublier ces 89 crédits à la con"),
            dialogue("bryonn", "Putain Romie arrête je suis dans la camionnette avec deux collègues là"),
            dialogue("bryonn", "J’ai 22 minutes avant la fin du shift"),
            dialogue("bryonn", "Je te jure je sens mon pouls dans les oreilles"),
            dialogue("bryonn", "Tu fais exprès hein ?"),
            dialogue("bryonn", "T’es en string + ce top depuis combien de temps ?"),
            dialogue("romie", "Depuis que j’ai franchi la porte. 18 minutes exactement"),
            dialogue("romie", "Et je suis déjà trempée rien qu’à t’imaginer rentrer"),
            dialogue("romie", "Tu vas faire quoi quand tu vas me voir comme ça ?"),
            dialogue("romie", "Dis-moi. En détail. J’ai besoin d’un programme pour patienter"),
            dialogue("bryonn", "Ok. Programme"),
            dialogue("bryonn", "1. Je ferme la porte avec mon pied sans lâcher ton regard"),
            dialogue("bryonn", "2. Je pose mon sac par terre, je m’approche sans parler"),
            dialogue("bryonn", "3. Je te prends par les hanches, je te soulève un peu pour que ton dos tape le mur"),
            dialogue("bryonn", "4. Je passe mes mains sous les découpes, je sens ta peau chaude, je descends lentement jusqu’à la jupe"),
            dialogue("bryonn", "5. Et après… je te fais payer les 89 crédits, mais en plusieurs fois"),
            dialogue("bryonn", "Très lentement"),
            dialogue("bryonn", "Très fort"),
            dialogue("romie", "… ok je bouge plus là"),
            dialogue("romie", "J’ai posé le téléphone sur la table basse et je me touche en lisant ça"),
            dialogue("romie", "Dépêche-toi de rentrer Bryonn"),
            dialogue("romie", "J’ai pas envie d’aller au bout sans toi"),
            dialogue("romie", "Vraiment pas"),
            dialogue("bryonn", "15 minutes"),
            dialogue("bryonn", "Je cours après le boulot"),
            dialogue("bryonn", "Garde le top. Et la jupe. Tout"),
            dialogue("bryonn", "Je t’aime sale gosse"),
            dialogue("romie", "Moi aussi sale livreur"),
            dialogue("romie", "Dépêche ❤️"),
            dialogue("system", "Session close."),
        ],
    )
